### ISSUE TITLE
Support debugger

### ISSUE THREAD

**Issue by simondotm** [simondotm/beeb-vsc#12]
This one's a biggy. 😄 
Would work with B2 only also.

**Comment by tommy9** [comment]
Definitely a biggy 😃 

It looks a really interesting challenge. I've done a bit of reading around the debug protocol adaptor. I think there are a few pieces to work out

- What emulator to use. I'm leaning towards jsbeeb because (1) being javascript it would be embeddable within the extension natively, (2) it appears you can access the emulator easily from other code (there is an example of this from the browser's javascript console and (3) it could probably show in a window within vscode. Ideally of course, multiple emulators would be supportable but it may require some collaboration with the maintainers to expose the API we would need
- How to build a source map from the BeebAsm code to the assembled code. Ideally a flag in BeebAsm could be used to create the information needed, I don't think it makes this currently. However, the output of BeebAsm when using the verbose -v flag does print all the labels in place as it produces the assembled code, so probably a small adjustment to the code that produces that would suffice
- Figuring out how to implement the debug adaptor. Microsoft's documentation looks quite good and they have sample code <https://microsoft.github.io/debug-adapter-protocol/> and there is this extension for the C64 that supports multiple assemblers and multiple debuggers <https://github.com/rolandshacks/vs64>. Very impressive.

**Comment by simondotm** [comment]
@tommy9 some great ideas here.

I definitely agree that an embedded jsbeeb instance could be awesome. Not sure what kind of external debugging capabilities it supports though (if any). At the very least, a vsc [WebView](https://code.visualstudio.com/api/extension-guides/webview) could be pretty cool for project previews etc.

On sourcemaps, I'm sure this topic has been discussed before somewhere - but I cant quite remember if it was on Slack or Stardot. But absolutely, having beebasm able to emit a symbol map would be a necessary precursor for debugging.

Beyond that, I'm guessing its a matter of having some API into whatever emulator is running to query machine state - stack/registers/memory/hardware would be necessary. I remember chatting with Tom Seddon about this a while ago because B2 has a local http service that supports queries like this.

Food for thought anyway!

**Comment by tommy9** [comment]
Closing this one down with the release of 0.3.0 but will no doubt need some new issues to refine the functionality.
