### ISSUE TITLE
POC - can we integrate JSBeeb?

### ISSUE THREAD

**Issue by simondotm** [simondotm/beeb-vsc#30]
After some mighty hacks, yes, it appears that we can. 

@tommy9 what do you think? 😄 

poc
![image](https://github.com/simondotm/beeb-vsc/assets/7404321/9bb4b6fd-6a6a-4603-8f97-1d19db4df703)

**Comment by tommy9** [comment]
Woah @simondotm, that's exciting! 🚀 
I saw on <https://github.com/mattgodbolt/jsbeeb/wiki/Debugger> that it is simple to read registers and memory, set and clear breakpoints etc. via the browser's javascript console, so hopefully could be adapted to the debug adaptor.

**Comment by simondotm** [comment]
That's a really awesome goal to aim for I think.

As a stepping stone toward that, I thought this might be initially useful as a preview feature for `.ssd` or `.dsd` or `.rom` files being developed in the workspace, since it is possible to add context menus in the extension.

For debugger integration, I suspect this will probably need some experimentation, and early version might be basic functionality (eg. without source maps etc.)

The next steps for this I think are to figure out how to add a modified version of jsbeeb to this extension. I'm currently thinking about importing the emulator as a package from Matt's [owlet](https://github.com/mattgodbolt/owlet-editor/blob/main/src/owlet.js) project.

Then add some wrapper scripts to apply mods to the scripts to suit, and finally, bundle it all up for use in the extension. 👍

**Comment by tommy9** [comment]
The owlet code looks really nice - clean and simple. I notice it has a Basic language definition too, so that could be a nice starting point for #10. 

Agree on the debugger integration needing to start small and just having a preview option is still a nice workflow. One possible starting point for debugging is ask jsbeeb for the disassembly of the Beeb's memory, then display that in a temporary window, allowing breakpoints to be hooked up. After that, maybe picking up the label information produced by beebasm via the -dd command line flag and/or the verbose output showing assembled output by address. Eventually, pending an update to beebasm, being able to use the source maps.

**Comment by simondotm** [comment]
Only the best for our massive userbase of 20 old skool beeb developers eh? 😂

**Comment by simondotm** [comment]
The answer to this ticket is yes, we can. 😄 
Have made good progress in #39 towards this.
Plus have Matt G's blessing to integtate JsBeeb also. 👍
