### ISSUE TITLE
Update docs for v0.2.0

### ISSUE THREAD

**Issue by simondotm** [simondotm/beeb-vsc#92]
* Need to add info about emulator
* Maybe optimize the readme and split into sub documents

**Comment by tommy9** [comment]
One suggestion for splitting the readme would be to separate the version history into CHANGELOG.md since that has special treatment in the extension marketplace. Looks like SUPPORT.md has special treatment too:

[https://code.visualstudio.com/api/working-with-extensions/publishing-extension#marketplace-integration](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#marketplace-integration)
